### PR TITLE
WIP: Updates for Julia 0.7

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by floswald** [comment]
hey @ssfrr, 
what's the status of this? julia v1.0 without testsetextensions is less fun.

**Comment by ararslan** [comment]
Julia 0.7.0-1.0.1 cannot support TestSetExtentions due to https://github.com/JuliaLang/julia/pull/24847.

**Comment by floswald** [comment]
yes I saw that. Is there any hope this is every going to change? sorry I can't really tell from looking that discussion on that issue.

**Comment by ararslan** [comment]
Maybe? I don't think it's at the top of anyone's priority list, so it'll end up happening when it happens, I suppose. If you want (or anyone else wants) to try digging into it, that would be welcome. It would require modifying the changes Jeff made in the linked Julia PR.

**Comment by ssfrr** [comment]
@floswald @ararslan this PR has been subsumed by #8.

**Pull request closed without merging**
